### ISSUE TITLE
Electrum-grs wallet (version 2.5.4): unverified

### ISSUE THREAD

**Issue by Vertimodo** [Groestlcoin/electrum-grs#10]
After the transaction has multiple confirmations, the transaction in the wallet keeps saying "unverified" under the "date" column.

**Comment by gruve-p** [comment]
Try running it overnight (24 hours)

**Comment by Vertimodo** [comment]
Thx for reply! Been running it for a long time, but will try :) I see a 2.8.3 version, is that out already, as i can't seem to find it?

**Comment by gruve-p** [comment]
We are still testing 2.8.3. We expect to release a new release within 2 months.

**Comment by Vertimodo** [comment]
Thx again for the fast responds, awesome support!

**Comment by Vertimodo** [comment]
Indeed, Problem has solved itself now after keeping the wallet running for a longer period. Thx :)
