### ISSUE TITLE
unverified transactions

### ISSUE THREAD

**Issue by MoeF1** [Groestlcoin/electrum-grs#11]
I loaded my electrum wallet with 2000 GRS some time ago and they show up in the History but keep being "unverified".
This issue has been ongoing for several months. strong "hodler" here.  ;-)
I tried withdrawing today to a mobile wallet and it worked without any flaws.

![grsbugelectrum](https://user-images.githubusercontent.com/36864592/36695293-2ba6c342-1b41-11e8-91d1-73bab1c00dae.png)

so seems to be working fine, just not showing the confirmations correctly.

**Comment by gruve-p** [comment]
Keep it running overnight for 24 hours and it will download the blockchain_headers into: %appdata%\Electrum-grs

Alternative: CLose wallet. Manually download from https://www.groestlcoin.org/blockchain_headers and place it into: %appdata%\Electrum-grs and wait 2 hours.
