### ISSUE TITLE
Trezor Safe 3

### ISSUE THREAD

**Issue by cthompstone** [Groestlcoin/electrum-grs#30]
Hi Guys, any chance you might be able to get Trezor's safe 3 working with the GRS wallet ?
Thanks

**Comment by gruve-p** [comment]
Are you using windows, osx or linux?

**Comment by cthompstone** [comment]
Wow, fast response.
Sorry yes, am using the appimage on Linux Mint.  i have the trezor safe 3 working on other wallets OK (I thought it might be udev related)  but on this wallet it can't find the hardware.
Thanks

**Comment by gruve-p** [comment]
Can you test this appimage and let us know if this solves your issue on the safe 3: 
https://github.com/Groestlcoin/electrum-grs/actions/runs/7628694438/artifacts/1190114178

**Comment by cthompstone** [comment]
Wow, thanks, result, it loads up and can see the addresses.
I've not tried to send/receive yet, as I don't have any GRS yet.
But it all seems fine.

**Comment by gruve-p** [comment]
Thank you for testing. We will release a new version for electrum-GRS somewhere in March 2024. Till then you can use the above appimage for testing.

**Comment by cthompstone** [comment]
Many thanks
