### ISSUE TITLE
ledger: (error getting device infos)  Exception : Invalid status 6702-6e00

### ISSUE THREAD

**Issue by simonunzio** [Groestlcoin/electrum-grs#31]
electrum-grs for windows can no longer communicate with the ledger. my wallet is inaccessible. I think this error is due to the bitcoin app installed on the ledger which has been causing this error since the last update

ledger: (error getting device infos)
    Exception : Invalid status 6e00

**Comment by gruve-p** [comment]
Can you give u smore info:
What electrum-grs version are you running?
Which bitcoin app and groestlcoin app versions do you have installed on the ledger?
What ledger hardware wallet do you have?

**Comment by simonunzio** [comment]
Electrum-grs 4.4.4 
Ledger Nano X
Bitcoin App on Ledger is release 2.1.3
I have tested on a windows 10 and windows 11 but the error is the same.
![image](https://github.com/Groestlcoin/electrum-grs/assets/50205427/ee55780c-f031-41c0-bce3-19495ee65445)

**Comment by gruve-p** [comment]
You are using the bitcoin app on ledger nano x with electrum-grs which is not going to work:

If you want to use for Bitcoin then open the bitcoin app on the ledger, download Electrum  and install it (and not Electrum-GRS).
If you want to use for Groestlcoin then install groestlcoin app on the ledger, start the application on the ledger nano x and use it with Electrum-GRS.
