### ISSUE TITLE
cannot connect to server electrum grs and via

### ISSUE THREAD

**Issue by Zete88** [Groestlcoin/electrum-grs#9]
hello guys i have a electrum viacoin and grscoin wallet and i cannot connect to the servers? any ideas?
maintence work? thanks so far

**Comment by gruve-p** [comment]
There are no maintenance on the electrum-grs servers.
Here is a list of GRS servers: https://1209k.com/bitcoin-eye/ele.php?chain=grs

If you still got problems: Try unticking SSL, save, close wallet. Start wallet, tick SSL, save.
